##
## Dovecot configuration
##
dovecot_config_version = 2.4.2
dovecot_storage_version = 2.4.2

protocols {
  imap = yes
  pop3 = yes
  submission = yes
  lmtp = yes
  sieve = yes
}

import_environment {
  DOVEADM_PASSWORD = %{env:DOVEADM_PASSWORD | default('supersecret')}
}

log_path = /dev/stdout

doveadm_password = $ENV:DOVEADM_PASSWORD

!include_try conf.d/*.conf
