##
## Dovecot configuration
##
dovecot_config_version = 2.4.2
dovecot_storage_version = 2.4.2

protocols {
  imap = yes
  pop3 = yes
  submission = yes
  lmtp = yes
  sieve = yes
}

import_environment {
  DOVEADM_PASSWORD = %{env:DOVEADM_PASSWORD | default('supersecret')}
}

log_path = /dev/stdout

mail_driver = maildir
mail_home = /var/mail/%{user | username | lower}
mail_path = %{home}/mail
mail_utf8_extensions = yes
mailbox_list_layout = index
mailbox_list_utf8 = yes

mail_uid = dovecot
mail_gid = root

mail_attribute {
  dict file {
    path = %{home}/dovecot-attributes
  }
}

imap_hibernate_timeout = 5s

protocol imap {
  mail_plugins {
    imap_sieve = yes
    imap_filter_sieve = yes
  }
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

doveadm_password = $ENV:DOVEADM_PASSWORD

!include_try conf.d/*.conf
