{{- if .Values.persistence.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "spamassassin.maintenance.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  schedule: {{ quote .Values.maintenance.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: maintenance
              image: {{ include "spamassassin.maintenance.image" . }}
              volumeMounts:
                - name: data
                  mountPath: /etc/spamassassin/sa-update-keys
                  subPath: sa-update-keys
                - name: data
                  mountPath: /var/lib/spamassassin
                  subPath: rules
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "spamassassin.persistence.claimName" . }}
          restartPolicy: Never
{{- end -}}