{{- if .Values.persistence.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-sa-update" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  schedule: {{ .Values.persistence.maintenance.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sa-update
              image: {{ include "spamassassin.image" . }}
              imagePullPolicy: IfNotPresent
              command:
                - maintenance
              volumeMounts:
                - name: data
                  mountPath: /var/lib/spamassassin
                  subPath: rules
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "spamassassin.persistence.claimName" . }}
{{- end -}}