apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if not .Values.persistence.enabled }}
      initContainers:
        - name: sa-update
          image: {{ include "spamassassin.maintenance.image" . }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/spamassassin
              subPath: rules
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "spamassassin.image" . }}
          ports:
            - name: spamd
              containerPort: 30783
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /user-prefs
              subPath: user-prefs
            - name: data
              mountPath: /var/lib/spamassassin
              subPath: rules
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "spamassassin.persistence.claimName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
