{{- if .Values.persistence.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spamassassin.initializationJob.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  template:
    spec:
      initContainers:
        - name: initialize
          image: {{ include "spamassassin.maintenance.image" . }}
          command:
            - /bin/sh
          args:
            - -c
            - mkdir -p /mnt/rules /mnt/user-prefs /mnt/sa-update-keys
          volumeMounts:
            - name: data
              mountPath: /mnt
      containers:
        - name: update
          image: {{ include "spamassassin.maintenance.image" . }}
          volumeMounts:
            - name: data
              mountPath: /etc/spamassassin/sa-update-keys
              subPath: sa-update-keys
            - name: data
              mountPath: /var/lib/spamassassin
              subPath: rules
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "spamassassin.persistence.claimName" . }}
      restartPolicy: Never
  backoffLimit: 3
{{- end -}}