apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-submission
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.submission.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.submission.service.type }}
  {{- with .Values.submission.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.submission.service.submissionPort }}
      targetPort: submission
      protocol: TCP
      name: submission
    - port: {{ .Values.submission.service.submissionsPort }}
      targetPort: submissions
      protocol: TCP
      name: submissions
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
