# This is a basic configuration that can easily be adapted to suit a standard
# installation. For more advanced options, see openmarc.conf(5) and/or
# /usr/share/doc/opendmarc/examples/opendmarc.conf.sample.

Background false
PidFile /run/opendmarc/opendmarc.pid
Socket inet:8893

Syslog true
SyslogFacility mail

AuthservID HOSTNAME
IgnoreHosts /etc/opendmarc/ignore.hosts

SoftwareHeader true
RejectFailures false

HistoryFile /run/opendmarc/opendmarc.dat

