apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/*.conf" }}
  {{ base $path }}: |
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
  {{- end }}