apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  dovecot.conf: |
    {{- tpl (.Files.Get "files/dovecot.conf") . | nindent 4 }}