apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    {{- range $service := .Values.services }}
    {{- range $listener := $service.listeners }}
    - name: {{ .name  }}
      port: {{ default .containerPort .servicePort }}
      protocol: TCP
      targetPort: {{ .name  }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
