apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: doveadm
      port: 443
      protocol: TCP
      targetPort: doveadm
    - name: lmtp
      port: 24
      protocol: TCP
      targetPort: lmtp
    - name: imap
      port: 143
      protocol: TCP
      targetPort: imap
    - name: imaps
      port: 993
      protocol: TCP
      targetPort: imaps
    - name: pop3
      port: 110
      protocol: TCP
      targetPort: pop3
    - name: pop3s
      port: 995
      protocol: TCP
      targetPort: pop3s
    - name: submission
      port: 587
      protocol: TCP
      targetPort: submission
    - name: submissions
      port: 465
      protocol: TCP
      targetPort: submissions
    - name: sieve
      port: 4190
      protocol: TCP
      targetPort: sieve
    - name: stats
      port: 9090
      protocol: TCP
      targetPort: stats
  selector:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
