apiVersion: v2
name: spamassassin
icon: https://upload.wikimedia.org/wikipedia/commons/7/73/Apache_SpamAssassin_logo.svg
description: A Helm chart creating a SpamAssassin Milter
type: application
version: 0.1.0
appVersion: "4.0.2"
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts