service submission-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener submission {
    port = 30587
  }
  inet_listener submissions {
    port = 30465
    ssl = yes
  }
}