mail_driver = maildir
mail_home = /var/mail/%{user | username | lower}
mail_path = %{home}/mail
mail_utf8_extensions = yes
mailbox_list_layout = index
mailbox_list_utf8 = yes

mail_uid = dovecot
mail_gid = root
first_valid_gid = 0

mail_attribute {
  dict file {
    path = %{home}/dovecot-attributes
  }
}

namespace inbox {
  type = private
  separator = /
  prefix =
  inbox = yes
}

namespace shared {
  type = shared
  separator = /
  prefix = shared/$user/

  mail_path = %{owner_home}/mail
  mail_index_private_path = %{home}/mail/shared/%{owner_user}

  subscriptions = no
  list = children
}
