default_internal_user = dovecot
default_login_user = dovecot
default_internal_group = dovecot

service imap-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener imap {
     port = 30143
  }
  inet_listener imaps {
     port = 30993
  }
}

service pop3-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener pop3 {
     port = 30110
  }
  inet_listener pop3s {
     port = 30995
  }
}

service submission-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener submission {
    port = 30587
  }
  inet_listener submissions {
    port = 30465
    ssl = yes
  }
}

service managesieve-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener sieve {
    port = 34190
  }
}

service lmtp {
   inet_listener lmtps {
     port = 30024
     ssl = yes
   }
}

service doveadm {
  inet_listener http {
    port = 8443
    ssl = yes
  }
}

service stats {
  process_min_avail = 1
  inet_listener http {
    port = 9090
    ssl = yes
  }
}