default_internal_user = dovecot
default_login_user = dovecot
default_internal_group = root

service imap-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener imap {
     port = %{env:IMAP_PORT | default('30143')}
  }
  inet_listener imaps {
     port = %{env:IMAPS_PORT | default('30993')}
     ssl = yes
  }
}

service pop3-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener pop3 {
     port = %{env:POP3_PORT | default('30110')}
  }
  inet_listener pop3s {
     port = %{env:POP3S_PORT | default('30995')}
     ssl = yes
  }
}

service submission-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener submission {
    port = %{env:SUBMISSION_PORT | default('30587')}
  }
  inet_listener submissions {
    port = %{env:SUBMISSIONS_PORT | default('30465')}
    ssl = yes
  }
}

service managesieve-login {
  process_min_avail = 1
  client_limit = 100
  chroot =

  inet_listener sieve {
    port = %{env:SIEVE_PORT | default('34190')}
  }
}

service lmtp {
   inet_listener lmtp {
     port = %{env:LMTP_PORT | default('30024')}
   }
}

service doveadm {
  inet_listener https {
    port = %{env:DOVEADM_PORT | default('8443')}
    ssl = yes
  }
}

service stats {
  process_min_avail = 1
  inet_listener https {
    port = %{env:STATS_PORT | default('9090')}
    ssl = yes
  }
}
