hostname = %{env:SUBMISSION_HOSTNAME}

submission_relay_host = %{env:SUBMISSION_RELAY_HOST | default('smtp')}
submission_relay_port = %{env:SUBMISSION_RELAY_PORT | default('25')}
submission_relay_ssl = %{env:SUBMISSION_RELAY_SSL | default('no')}
submission_relay_ssl_verify = %{env:SUBMISSION_RELAY_SSL_VERIFY | default('yes')}
submission_relay_trusted = %{env:SUBMISSION_RELAY_TRUSTED | default('no')}

submission_relay_user = $ENV:SUBMISSION_RELAY_USER
submission_relay_master_user = $ENV:SUBMISSION_RELAY_MASTER_USER
submission_relay_password = $ENV:SUBMISSION_RELAY_PASSWORD
