apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-smtpd" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.smtpd.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.smtpd.service.type }}
  {{- with .Values.smtpd.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.smtpd.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
