apiVersion: v2
name: dovecot
description: A Helm chart to deploy Dovecot into Kubernetes
type: application
version: 0.3.5
appVersion: "2.4.2"
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
