# Default values for dovecot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:

replicaCount: 1

image:
  registry: quay.io/ludovicus
  repository: kubemail
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

authentication:
  oauth2:
    enabled: false
    
  ldap:
    enabled: false
    uris:
      - ldap://ak-outpost-authentik-ldap.authentik.svc.cluster.local
    base: dc=galensfamily,dc=org
    authUser: uid=dovecot,ou=users,dc=galensfamily,dc=org
    authPassword: 4sULRt4iNMABHPZ
    filter: (&(objectClass=goauthentik.io/ldap/user)(|(uid=%{user})(mail=%{user}))) 
    passdb:
      bind: true
      template: uid=%{user},ou=users,dc=galensfamily,dc=org

lmtp:
  enabled: true
  ssl: false
  service:
    annotations: {}
    type: ClusterIP
    port:
    externalIPs: []

sieve:
  enabled: true
  ssl: true
  spamassassin:
    host:
    port:
  service:
    annotations: {}
    type: ClusterIP
    port:
    externalIPs: []

submission:
  hostname:
  service:
    type: ClusterIP
    annotations: {}
    externalIPs: []
    port:
    sslPort:
  relay:
    host:
    port:
    # can be one of (starttls, smtps, no) defaults to no
    ssl:
    sslVerify: true
    trusted: true
    credentials:
      master: false
      secret:
        name:
        usernameKey:
        passwordKey:

doveadm:
  service:
    create: true
    port:
  ingress:
    enabled: false
    hostname:

stats:
  service:
    create: true
    port: 9090

tls:
  secretName:

service:
  annotations: {}
  type: ClusterIP
  externalIPs: []

persistence:
  enabled: true
  existingClaim:
  storageClass:
  size: 50Gi
  accessModes:
    - ReadWriteOnce

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
