apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  aliases: |
    MAILER_DAEMON: postmaster
    postmaster: root
    {{- range .Values.aliases }}
    {{- . | indent 4}}
    {{- end }}
  main.cf: |
    {{- tpl (.Files.Get "files/main.cf") . | nindent 4 }}
  master.cf: |
    {{- tpl (.Files.Get "files/master.cf") . | nindent 4 }}
